server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

jasypt:
  encryptor:
    password: shop

# spring
spring:
  datasource:
    url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(LQi0FkhtShKQ3PZFfBwj6w==)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver

  redis:
    host: 192.168.0.146
    database: 0
    port: 6379
    timeout: 3000ms

  data:
    mongodb:
      uri: mongodb://192.168.0.146:27017/shop
    elasticsearch:
      cluster-name: d2cmall-es
      cluster-nodes: 192.168.0.146:9300

  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.d2c.shop.modules.*.model
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
    sql-parser-cache: false
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    cache-enabled: false

# ignored-urls
ignored:
  urls:
    - /b_api/**
    - /c_api/**
    - /test/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /back/user/expired
    - /back/user/insert

#logging:
#  level:
#    root: debug
